// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=./mock_sqs/mock_client.go -package=mock_sqs
//

// Package mock_sqs is a generated GoMock package.
package mock_sqs

import (
	context "context"
	reflect "reflect"

	sqs "github.com/mickamy/go-sqs-worker/sqs"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Dequeue mocks base method.
func (m *MockClient) Dequeue(ctx context.Context, queueURL string, waitTimeSeconds int) (*string, sqs.CleanUp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dequeue", ctx, queueURL, waitTimeSeconds)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(sqs.CleanUp)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Dequeue indicates an expected call of Dequeue.
func (mr *MockClientMockRecorder) Dequeue(ctx, queueURL, waitTimeSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dequeue", reflect.TypeOf((*MockClient)(nil).Dequeue), ctx, queueURL, waitTimeSeconds)
}

// Enqueue mocks base method.
func (m *MockClient) Enqueue(ctx context.Context, queueURL, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, queueURL, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockClientMockRecorder) Enqueue(ctx, queueURL, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockClient)(nil).Enqueue), ctx, queueURL, message)
}

// EnqueueWithDelay mocks base method.
func (m *MockClient) EnqueueWithDelay(ctx context.Context, queueURL, message string, delaySeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueWithDelay", ctx, queueURL, message, delaySeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueWithDelay indicates an expected call of EnqueueWithDelay.
func (mr *MockClientMockRecorder) EnqueueWithDelay(ctx, queueURL, message, delaySeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueWithDelay", reflect.TypeOf((*MockClient)(nil).EnqueueWithDelay), ctx, queueURL, message, delaySeconds)
}
